/*******************************************************************************
 *  Jaspersoft Open Studio - Eclipse-based JasperReports Designer.
 *  Copyright (C) 2005, 2010 Jaspersoft Corporation. All rights reserved.
 *  http://www.jaspersoft.com
 *  
 *  Unless you have purchased a commercial license agreement from Jaspersoft,
 *  the following license terms apply:
 *  
 *  This program is part of iReport.
 *  
 *  iReport is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *  
 *  iReport is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU Affero General Public License for more details.
 *  
 *  You should have received a copy of the GNU Affero General Public License
 *  along with iReport. If not, see <http://www.gnu.org/licenses/>.
 *******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jaspersoft_studio_editor_java2d_LinuxImageRenderer */

#ifndef _Included_com_jaspersoft_studio_editor_java2d_LinuxImageRenderer
#define _Included_com_jaspersoft_studio_editor_java2d_LinuxImageRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jaspersoft_studio_editor_java2d_LinuxImageRenderer
 * Method:    renderImage
 * Signature: (IIIIIII[III)V
 */
JNIEXPORT void JNICALL Java_com_jaspersoft_studio_editor_java2d_LinuxImageRenderer_renderImage
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
