/*******************************************************************************
 * Copyright (C) 2005 - 2014 TIBCO Software Inc. All rights reserved.
 * http://www.jaspersoft.com.
 * 
 * Unless you have purchased  a commercial license agreement from Jaspersoft,
 * the following license terms  apply:
 * 
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 ******************************************************************************/
/*
* generated by Xtext
*/
package com.jaspersoft.studio.editor.jrexpressions.ui.contentassist;

import java.util.Collections;
import java.util.List;

import net.sf.jasperreports.engine.JRField;
import net.sf.jasperreports.engine.JRParameter;
import net.sf.jasperreports.engine.JRVariable;
import net.sf.jasperreports.expressions.annotations.JRExprFunctionBean;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.swt.graphics.Image;
import org.eclipse.wb.swt.ResourceManager;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.ui.editor.XtextSourceViewer;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;

import com.jaspersoft.studio.editor.expression.ExpressionContext;
import com.jaspersoft.studio.editor.expression.ExpressionContextUtils;
import com.jaspersoft.studio.editor.expression.FunctionsLibraryUtil;
import com.jaspersoft.studio.editor.jrexpressions.ui.JRExpressionsUIPlugin;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class JavaJRExpressionProposalProvider extends AbstractJavaJRExpressionProposalProvider {
	
	@Override
	public void complete_JRFieldObj(EObject model, RuleCall ruleCall, ContentAssistContext context, ICompletionProposalAcceptor acceptor) {
		ExpressionContext exprContext=(ExpressionContext) ((XtextSourceViewer) context.getViewer()).getData(ExpressionContext.ATTRIBUTE_EXPRESSION_CONTEXT);
		if(exprContext!=null){
			List<JRField> allFields = ExpressionContextUtils.getAllDatasetsFields(exprContext);
			for(JRField field : allFields){
				acceptor.accept(createCompletionProposal(
						"$F{" + field.getName() + "}", "$F{" + field.getName() + "}", getFieldIconImg(), context));   //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$
			}
		}
	}
	
	@Override
	public void complete_JRVariableObj(EObject model, RuleCall ruleCall, ContentAssistContext context, ICompletionProposalAcceptor acceptor) {
		ExpressionContext exprContext=(ExpressionContext) ((XtextSourceViewer) context.getViewer()).getData(ExpressionContext.ATTRIBUTE_EXPRESSION_CONTEXT);
		if(exprContext!=null){
			List<JRVariable> allVariables = ExpressionContextUtils.getAllDatasetsVariables(exprContext);
			for(JRVariable var : allVariables){
				acceptor.accept(createCompletionProposal(
						"$V{" + var.getName() + "}", "$V{" + var.getName() + "}", getVariableIconImg(), context));   //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$
			}
		}
	}
	
	@Override
	public void complete_JRParameterObj(EObject model, RuleCall ruleCall, ContentAssistContext context, ICompletionProposalAcceptor acceptor) {
		ExpressionContext exprContext=(ExpressionContext) ((XtextSourceViewer) context.getViewer()).getData(ExpressionContext.ATTRIBUTE_EXPRESSION_CONTEXT);
		if(exprContext!=null){
			List<JRParameter> allParameters = ExpressionContextUtils.getAllDatasetsParameters(exprContext);
			for(JRParameter param : allParameters){
				acceptor.accept(createCompletionProposal(
						"$P{" + param.getName() + "}", "$P{" + param.getName() + "}", getParameterIconImg(), context));   //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$
			}
		}
	}
	
	@Override
	public void complete_JRResourceBundleKeyObj(EObject model, RuleCall ruleCall, ContentAssistContext context,	ICompletionProposalAcceptor acceptor) {
		ExpressionContext exprContext=(ExpressionContext) ((XtextSourceViewer) context.getViewer()).getData(ExpressionContext.ATTRIBUTE_EXPRESSION_CONTEXT);
		if(exprContext!=null) {
			List<String> rbKeys = ExpressionContextUtils.getResourceBundleKeys(exprContext);
			for(String k : rbKeys) {
				acceptor.accept(createCompletionProposal(
						"$R{" + k + "}", "$R{" + k + "}", getResourceBundleKeyIconImg(), context));   //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$ //$NON-NLS-4$
			}
		}
	}
	
	@Override
	public void complete_FullMethodName(EObject model, RuleCall ruleCall, ContentAssistContext context, ICompletionProposalAcceptor acceptor) {
		List<JRExprFunctionBean> allFunctions = FunctionsLibraryUtil.getAllFunctions();
		Collections.sort(allFunctions);
		for(JRExprFunctionBean funct : allFunctions){
			acceptor.accept(createCompletionProposal(
					funct.getId(), funct.getName(), getMethodNameIconImg(), context));  
		}
	}
	
	
	/*
	 * Get JRParameter icon image.
	 */
	private Image getParameterIconImg(){
		return ResourceManager.getPluginImage(JRExpressionsUIPlugin.PLUGIN_ID, "/resources/icons/parameters-16.png"); //$NON-NLS-1$
	}
	
	/*
	 * Get JRVariable icon image.
	 */
	private Image getVariableIconImg(){
		return ResourceManager.getPluginImage(JRExpressionsUIPlugin.PLUGIN_ID, "/resources/icons/variables-16.png"); //$NON-NLS-1$
	}

	/*
	 * Get JRField icon image.
	 */
	private Image getFieldIconImg(){
		return ResourceManager.getPluginImage(JRExpressionsUIPlugin.PLUGIN_ID, "/resources/icons/fields-16.png"); //$NON-NLS-1$
	}
	
	/*
	 * Get JRResourceBundleKey icon image.
	 */
	private Image getResourceBundleKeyIconImg(){
		return ResourceManager.getPluginImage(JRExpressionsUIPlugin.PLUGIN_ID, "/resources/icons/resourcebundles-16-icon.png"); //$NON-NLS-1$
	}
	
	/*
	 * Get the icon image for a proposed function.
	 */
	private Image getMethodNameIconImg(){
		return ResourceManager.getPluginImage(JRExpressionsUIPlugin.PLUGIN_ID, "/resources/icons/methodName.gif"); //$NON-NLS-1$
	}
	
}
